---
title: "Pesquisa"
listing:
  - id: research
    contents: "**/*/index.qmd"
    type: grid
    fields: [image, date, title, subtitle]
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    page-size: 10 
---

Para informações mais atualizadas/detalhadas, consulte o [currículo lattes](http://lattes.cnpq.br/5150665880581477).

## Formação

-   (2019-2024) - Doutorado em Ciências Ambientais, Universidade de São Paulo, Brasil

-   (2016-2018) - Mestrado em Ciências, no Programa de Pós-graduação em Análise Ambiental Integrada, na UNIFESP - Campus Diadema.

-   (2012-2015) - Graduação em Gestão Ambiental, na EACH/USP.

## Áreas de interesse

-   Recursos hídricos / Governança da água

-   Transparência e acesso à informação

-   Ciência de dados aplicado à ciências ambientais

## Grupos de pesquisa

-   (2024-Atual) [ICOLMA - The impact of Covid19 on livelihoods, mobility and accessibility of marginalized groups](https://ips.raumplanung.tu-dortmund.de/en/research/projects/icolma/)

<!-- -->

-   (2019-Atual) - [Grupo de Acompanhamento e Estudos em Governança Ambiental](https://sites.usp.br/govamb/pagina-2/)

-   (2019-2021) - [GovernAgua -- Transforming water governance in South America: from reaction to adaptation and anticipation](https://saras-institute.org/governagua-transforming-water-governance-in-south-america-from-reaction-to-adaptation-and-anticipation/) - Agência Financiadora: Inter-American Institute for Global Change Research (IAI)

-   (2018-2022) - [MacroAmb: Governança Ambiental da Macrometrópole Paulista face à variabilidade climática](https://pesquisa.ufabc.edu.br/macroamb/governanca-de-saneamento-ambiental-e-analises-das-vulnerabilidades-na-macrometropole-paulista/) - Projeto temático FAPESP nº 2015-03804-9

## Pesquisas selecionadas

-   Em construção!

::: {#research}
:::
